model_util: Use ofstream offset type (#115)
libc++ use long long instead of long for the offset causing ambiguity.

onnxoptimizer/model_util.cc:193:35: error: use of overloaded operator '-' is ambiguous (with operand types 'pos_type' (aka 'fpos<__mbstate_t>') and 'int64_t' (aka 'long'))
  info.length = data_file.tellp() - info.offset;
                ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~

Signed-off-by: Raul Tambre <raul.tambre@clevon.com>
Co-authored-by: Raul Tambre <raul.tambre@clevon.com>